# Configuration for request-info - https://github.com/behaviorbot/request-info

# *OPTIONAL* Comment to reply with
# Group SAGE doing Request pull info - LAB_4
# Can be either a string :
requestInfoReplyComment:
  We would appreciate it if you could provide us with more information about this issue at hand, and thanks in advance/pr!

# Or an array:
# requestInfoReplyComment:
#  - Ah no! young blade! That was a trifle short!
#  - Thanks for the help!
#  - Tell me more !
#  - I am sure you can be more effusive
updateDocsComment: >
  Thanks for opening this pull request! The maintainers of this repository would appreciate it if you would update some of our documentation based on your changes.
  
newPRWelcomeComment: >
  Thanks so much for opening your first PR here!

firstPRMergeComment: >
  Congrats on merging your first pull request here! :tada: How awesome!

newIssueWelcomeComment: >
  Thanks for opening this issue, a maintainer will get back to you shortly!

# *OPTIONAL* default titles to check against for lack of descriptiveness
# MUST BE ALL LOWERCASE
requestInfoDefaultTitles:
  - update readme.md
  - updates

# *OPTIONAL* Label to be added to Issues and Pull Requests with insufficient information given
requestInfoLabelToAdd: needs-more-info

# *OPTIONAL* Require Pull Requests to contain more information than what is provided in the PR template
# Will fail if the pull request's body is equal to the provided template
checkPullRequestTemplate: true

# *OPTIONAL* Only warn about insufficient information on these events type
# Keys must be lowercase. Valid values are 'issue' and 'pullRequest'
requestInfoOn:
  pullRequest: true
  issue: true

# *OPTIONAL* Add a list of people whose Issues/PRs will not be commented on
# keys must be GitHub usernames
requestInfoUserstoExclude:
  - hiimbex
  - bexo
  - Siddharth Chauhan
  - Enitan Mautin
  - John Adekunle
